### ISSUE TITLE
Buildah tasks fail with unshare(CLONE_NEWUSER)

### ISSUE THREAD

**Issue by MichaelFitzurka** [marrober/pipelineBuildExample#5]
I've been struggling to follow your example for a few days, and I have been updating with your recent changes:

Yet every time I get to a buildah task I get the following error:

Error during unshare(CLONE_NEWUSER): Invalid argument
time="2021-09-30T15:18:18Z" level=error msg="error parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
time="2021-09-30T15:18:18Z" level=error msg="(unable to determine exit status)"

General research has indicated that this is a issue with buildah needing privileged access or sys admin capabilities.
But I am using an out-of-the box version of OpenShift on AWS ver 4.8.13 and the latest buildah image from RH's container repository, and my understand was that buildah did not need privileged access and it did not need CAP_SYS_ADMIN, yet I'm getting this error.

Likely this is a buildah issue or an OCP env issue on my side or something to do with security contexts that I admittedly am not an expert in ... but I was wondering, since this comes up in your example app here, if you have seen the same issue and know how to address it.

PS. If I find a solution elsewhere, I will update here.
PSS. Love the ArgoCD inclusion, had to divert attention to that for awhile to learn it and I'm glad I did!

**Comment by marrober** [comment]
Hi Michael,

I have to admit that I have not seen that error before so it could be a
permission problem within that environment. I will take a better look
tomorrow and see what I can find. I have been making a lot of changes to
it, as you can see, over the last few days and some of that was because the
demonstration broke due to a change in the S2I process. I now have that
resolved with some additions to the pom.xml file.

The Argo CD content came from doing other GitOps examples and I decided to
add it in here as an alternative to the shell scripts that create the
resources.

I hope to get back to you soon with some useful info on how to overcome the
problem.

Mark

Mark Roberts

Senior Solution Architect

Red Hat <https://www.redhat.com/>

***@***.*** ***@***.***>
M: 07887-850270
<https://www.redhat.com/>

**Comment by MichaelFitzurka** [comment]
Thanks for the quick reply.

According to a closed buildah issue:
https://github.com/containers/buildah/issues/3455#issue-972033016

This looks to be a broader SCC issue - trying to reach out to @cgruver (Red Hatter that created and closed the issue.)

Will update for posterity if I find the solution - but this isn't on you - thanks!

**Comment by MichaelFitzurka** [comment]
Closing - I believe this is linked to my Dynatrace Operator and opened a ticket with them. https://github.com/Dynatrace/dynatrace-operator/issues/275#issue-1013679986
